###
PUT http://localhost:8080/designation/001
Content-type: application/json

{
  "desigDesc": "Hi there!",
  "insUser": "Rahim Mia",
  "updUser": "Karim Mia"
}
###
GET http://localhost:8080/designation
###
DELETE http://localhost:8080/designation/001
Content-Type: application/json
