### Send POST request with json body
POST http://localhost:8080/designation
Content-Type: application/json

{
  "desigCode": "001",
  "desigDesc": "Mathematics Teacher",
  "insUser": "Teacher",
  "updUser": "No"
}
### Get request with json body
GET http://localhost:8080/designation
Content-Type: application/json