### Send POST request with json body
POST http://localhost:8080/designation
Content-Type: application/json

{
  "desigCode": "010",
  "desigDesc": "Bengali Teacher",
  "insUser": "Full-Time Teacher"
}

### Get request with json body
GET http://localhost:8080/designation
Content-Type: application/json