### Send POST request with json body
POST http://localhost:8080/designation
Content-Type: application/json

{
  "desigCode": "071",
  "desigDesc": "Korean Teacher",
  "insUser": "Mahid"

}
### Get request with json body
GET http://localhost:8080/designation
Content-Type: application/json