### Send POST request with json body
POST http://localhost:8080/teacher
Content-Type: application/json

{
  "companyCode" : "001",
  "companyBranchCode" : "01",
  "financeCode" : "01",
  "projectCode" : "01",
  "componentCode" : "01",
  "teacherId" : "A21",
  "teacherName" : "Shohedul Khan",
  "designationCode": "001",
  "insUser" : "Maria"
}

### GetRequest with json body
GET http://localhost:8080/teacher